# Generated by Django 2.0 on 2017-12-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='word2image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=512)),
                ('translation', models.CharField(max_length=512)),
                ('pic1', models.CharField(max_length=1024)),
                ('pic2', models.CharField(max_length=1024)),
                ('pic3', models.CharField(max_length=1024)),
                ('pic4', models.CharField(max_length=1024)),
                ('approvedPic1', models.BooleanField(default=False)),
                ('approvedPic2', models.BooleanField(default=False)),
                ('approvedPic3', models.BooleanField(default=False)),
                ('approvedPic4', models.BooleanField(default=False)),
                ('lastUpdate', models.DateField()),
            ],
        ),
    ]
