# Generated by Django 2.0 on 2017-12-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word2image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word2image',
            name='pic1',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='word2image',
            name='pic2',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='word2image',
            name='pic3',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='word2image',
            name='pic4',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
